### ISSUE TITLE
Installation ok, but phonetic evaluation has error

### ISSUE THREAD

**Issue by syfengcuhk** [bootphon/zerospeech2021#1]
Dear developers,

I installed zerospeech2021. 
The function 'zerospeech2021-validate' works well.
The function zerospeech2021-evaluation works normally on lexical, syntactic and semantic, but has an error on phonetic:

> File ".../anaconda3/envs/zerospeech2021_2/lib/python3.8/site-packages/zerospeech2021-0.1-py3.8-linux-x86_64.egg/zerospeech2021/phonetic_eval/ABX_src/abx_group_computation.py", line 89, in get_theta_group_dtw
>   File ".../anaconda3/envs/zerospeech2021_2/lib/python3.8/site-packages/zerospeech2021-0.1-py3.8-linux-x86_64.egg/zerospeech2021/phonetic_eval/ABX_src/abx_group_computation.py", line 80, in get_distance_group_dtw
> AttributeError: module 'libri_light_dtw' has no attribute 'dtw_batch'

I can see there is a bug when trying to "import libri_light_dtw as dtw" in the file "abx_group_computation.py". Presumably the program cannot find a correct path to libri_light_dtw? Not sure my guess is correct or not.
Can anyone please check this? Thank you in advance.

**Comment by mmmaat** [comment]
Hi,

The `dtw_batch` function is implemented in the Cython file [ABX_scr/dtw.py](https://github.com/bootphon/zerospeech2021/blob/master/zerospeech2021/phonetic_eval/ABX_src/dtw.pyx#L13). You can simply test its installation by doing, in a Python terminal: `from libri_light_dtw import dtw_batch`.

I'm suspecting you have an installation issue. Did you correctly ran `python setup.install`? This is compiling the Cython code and makes it available as a Python import. During installation you must see some messages relative to compilation of `dtw.pyx`:
```bash
building 'libri_light_dtw' extension
creating build
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/zerospeech2021
creating build/temp.linux-x86_64-3.8/zerospeech2021/phonetic_eval
creating build/temp.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src
gcc -pthread -B .../.conda/envs/zerospeech2021/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I.../.conda/envs/zerospeech2021/lib/python3.8/site-packages/numpy/core/include -I.../.conda/envs/zerospeech2021/include/python3.8 -c zerospeech2021/phonetic_eval/ABX_src/dtw.c -o build/temp.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src/dtw.o
In file included from .../.conda/envs/zerospeech2021/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
                 from .../.conda/envs/zerospeech2021/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from .../.conda/envs/zerospeech2021/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from zerospeech2021/phonetic_eval/ABX_src/dtw.c:619:
.../.conda/envs/zerospeech2021/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
creating build/lib.linux-x86_64-3.8
gcc -pthread -shared -B .../.conda/envs/zerospeech2021/compiler_compat -L.../.conda/envs/zerospeech2021/lib -Wl,-rpath=.../.conda/envs/zerospeech2021/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src/dtw.o -o build/lib.linux-x86_64-3.8/libri_light_dtw.cpython-38-x86_64-linux-gnu.so
```

**Comment by syfengcuhk** [comment]
Hi!
Re. to your advice in python try
$ from libri_light_dtw import dtw_batch
This gave 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'dtw_batch' from 'libri_light_dtw' (/home/nfs/siyuanfeng/.cache/Python-Eggs/zerospeech2021-0.1-py3.8-linux-x86_64.egg-tmp/libri_light_dtw.cpython-38-x86_64-linux-gnu.so)

THank you for the suggestion. I finally found out an alternative way to solve this issue, using an alternative method.
I added a path to the head of abx_group_computation.py, like:
`sys.path.insert(1, 'my_path_to_zerospeech2021/build/lib.linux-x86_64-3.8')`
Because I can see there is a libri_light_dtw.cpython-38-x86_64-linux-gnu.so file under build/lib.linux-x86_64-3.8/ directory.

While the phonetic evaluation works fine now, I am curious why in my machine the python can't find a correct path to libri_light_dtw package. 

Best
Siyuan

**Comment by MingjieChen** [comment]
Hi,

I am having the same error.

I check the message from running python setup.py install,  I didn't find any gcc compiling log info as you shown. 


And here is my log info: 


running install
running bdist_egg
running egg_info
writing zerospeech2021.egg-info/PKG-INFO
writing dependency_links to zerospeech2021.egg-info/dependency_links.txt
writing entry points to zerospeech2021.egg-info/entry_points.txt
writing top-level names to zerospeech2021.egg-info/top_level.txt
reading manifest file 'zerospeech2021.egg-info/SOURCES.txt'
writing manifest file 'zerospeech2021.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying zerospeech2021/phonetic_eval/ABX_src/abx_group_computation.py -> build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic.py -> build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/zerospeech2021/semantic.py -> build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/zerospeech2021/meta.py -> build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/zerospeech2021/exception.py -> build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/zerospeech2021/lexical.py -> build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/zerospeech2021/syntactic.py -> build/bdist.linux-x86_64/egg/zerospeech2021
creating build/bdist.linux-x86_64/egg/zerospeech2021/cli
copying build/lib.linux-x86_64-3.8/zerospeech2021/cli/validate.py -> build/bdist.linux-x86_64/egg/zerospeech2021/cli
copying build/lib.linux-x86_64-3.8/zerospeech2021/cli/evaluate.py -> build/bdist.linux-x86_64/egg/zerospeech2021/cli
copying build/lib.linux-x86_64-3.8/zerospeech2021/cli/__init__.py -> build/bdist.linux-x86_64/egg/zerospeech2021/cli
creating build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/eval_ABX.py -> build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval
creating build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src/abx_iterators.py -> build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src/abx_group_computation.py -> build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/ABX_src/__init__.py -> build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/CPC_loader.py -> build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval
copying build/lib.linux-x86_64-3.8/zerospeech2021/phonetic_eval/__init__.py -> build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval
copying build/lib.linux-x86_64-3.8/zerospeech2021/__init__.py -> build/bdist.linux-x86_64/egg/zerospeech2021
copying build/lib.linux-x86_64-3.8/libri_light_dtw.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic.py to phonetic.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/semantic.py to semantic.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/meta.py to meta.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/exception.py to exception.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/lexical.py to lexical.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/syntactic.py to syntactic.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/cli/validate.py to validate.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/cli/evaluate.py to evaluate.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/cli/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/eval_ABX.py to eval_ABX.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src/abx_iterators.py to abx_iterators.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src/abx_group_computation.py to abx_group_computation.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/ABX_src/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/CPC_loader.py to CPC_loader.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/phonetic_eval/__init__.py to __init__.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/zerospeech2021/__init__.py to __init__.cpython-38.pyc
creating stub loader for libri_light_dtw.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/libri_light_dtw.py to libri_light_dtw.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying zerospeech2021.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying zerospeech2021.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying zerospeech2021.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying zerospeech2021.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying zerospeech2021.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying zerospeech2021.egg-info/zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
creating 'dist/zerospeech2021-0.1-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing zerospeech2021-0.1-py3.8-linux-x86_64.egg
Removing /share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/zerospeech2021/lib/python3.8/site-packages/zerospeech2021-0.1-py3.8-linux-x86_64.egg
Copying zerospeech2021-0.1-py3.8-linux-x86_64.egg to /share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/zerospeech2021/lib/python3.8/site-packages
zerospeech2021 0.1 is already the active version in easy-install.pth
Installing zerospeech2021-evaluate script to /share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/zerospeech2021/bin
Installing zerospeech2021-validate script to /share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/zerospeech2021/bin

Installed /share/mini1/sw/std/python/anaconda3-2019.07/v3.7/envs/zerospeech2021/lib/python3.8/site-packages/zerospeech2021-0.1-py3.8-linux-x86_64.egg
Processing dependencies for zerospeech2021==0.1
Finished processing dependencies for zerospeech2021==0.1

**Comment by jdzikowski** [comment]
I'm having the same issue which was resolved by using @syfengcuhk's workaround. Prior to running `python setup.py install` from the instructions, prepend the following lines to `zerospeech2021/phonetic_eval/ABX_src/abx_group_computation.py`
```
import sys
sys.path.insert(1, 'my_path_to_zerospeech2021/build/lib.linux-x86_64-3.8')
```
Then run  `python setup.py install` to finish installation.

**Comment by mmmaat** [comment]
Hi, thanks for reporting that issue. I updated the `setup.py` and this should be fixed now. Can you confirm?

**Comment by jdzikowski** [comment]
Yes, it now works for me out of the box. Thanks
