### ISSUE TITLE
Bug in lexical.py

### ISSUE THREAD

**Issue by marianne-m** [bootphon/zerospeech2021#5]
I found a bug in `lexical.py` , line 145:
`data.drop(columns=['phones', 'filename'], inplace=True)` raises the following error : 
`KeyError: "['filename'] not found in axis"`

`'filename'` is not a column, it's the index

`data.drop(columns=['phones'], inplace=True)` should work.

**Comment by mmmaat** [comment]
Hi Marianne,
Pandas version is not specified in the requirements, it may be the source of the bug... (https://pandas.pydata.org/docs/whatsnew/v1.3.0.html) Which version of pandas are you using? For me it used to work on `pandas-1.2.4`. You can use `conda env export | grep pandas` to get the version.

**Comment by marianne-m** [comment]
Hi !
Yes that was the problem. I was using `pandas-1.1.3`, after upgrading to `pandas-1.2.4` everything works.
Thank you !
